services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celeryworker:
    build: .
    command: celery -A app.core.celery.celery_app worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - api

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recall
      POSTGRES_PASSWORD: recall
      POSTGRES_DB: recallify
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: